// Catálogo único de ícones, agora apoiado no Hugeicons (conjunto gratuito).
// Os nomes são os mesmos de antes, então nada no resto do projeto precisou mudar:
// <Icon name="sacola" /> continua valendo, e o seletor do painel (src/fields/icone.ts)
// segue lendo o `label` daqui.
//
// Ícone novo: importe o export do @hugeicons/core-free-icons e registre abaixo.
import {
  Activity03Icon,
  Alert02Icon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowReloadHorizontalIcon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  Atom01Icon,
  Book02Icon,
  Calendar03Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CandyIcon,
  CandyOffIcon,
  ChartUpIcon,
  CheckmarkBadge01Icon,
  CheckmarkCircle02Icon,
  Clock01Icon,
  CoffeeBeansIcon,
  CookieIcon,
  Cupcake01Icon,
  DeliveryTruck01Icon,
  DeliveryTruck02Icon,
  Dish01Icon,
  DropletIcon,
  Facebook01Icon,
  FlashIcon,
  GiftIcon,
  HelpCircleIcon,
  InformationCircleIcon,
  InjectionIcon,
  InstagramIcon,
  Leaf01Icon,
  Medicine01Icon,
  Menu01Icon,
  Message01Icon,
  Moon02Icon,
  PauseIcon,
  PlayIcon,
  PlusSignCircleIcon,
  PlusSignIcon,
  ReceiptIcon,
  Restaurant01Icon,
  RiceBowl01Icon,
  Sad01Icon,
  Shield01Icon,
  ShieldCheckIcon,
  ShoppingBag01Icon,
  ShoppingBag02Icon,
  SparklesIcon,
  SproutIcon,
  SquareLock01Icon,
  StarIcon,
  Store01Icon,
  Sun03Icon,
  Tick02Icon,
  TiktokIcon,
  VolumeHighIcon,
  VolumeOffIcon,
  WhatsappIcon,
  YoutubeIcon,
  Invoice01Icon,
} from '@hugeicons/core-free-icons'
import type { IconSvgElement } from '@hugeicons/react'

export type IconDef = { icon: IconSvgElement; label: string; stroke?: number }

export const icons = {
  // navegação e controles
  menu: { icon: Menu01Icon, label: 'Menu', stroke: 2.2 },
  fechar: { icon: Cancel01Icon, label: 'Fechar' },
  'x-pequeno': { icon: Cancel01Icon, label: 'X pequeno (tentativas)' },
  'x-negrito': { icon: Cancel01Icon, label: 'X (traço grosso)', stroke: 2.6 },
  'x-circulo': { icon: CancelCircleIcon, label: 'X em círculo' },
  'chevron-cima': { icon: ArrowUp01Icon, label: 'Chevron para cima', stroke: 2.4 },
  'chevron-baixo': { icon: ArrowDown01Icon, label: 'Chevron para baixo', stroke: 2.4 },
  'chevron-esquerda': { icon: ArrowLeft01Icon, label: 'Chevron para a esquerda', stroke: 2.4 },
  'chevron-direita': { icon: ArrowRight01Icon, label: 'Chevron para a direita', stroke: 2.4 },
  'seta-direita': { icon: ArrowRight02Icon, label: 'Seta para a direita', stroke: 2.2 },
  mais: { icon: PlusSignIcon, label: 'Mais' },
  'mais-botao': { icon: PlusSignCircleIcon, label: 'Mais (botão)' },
  check: { icon: Tick02Icon, label: 'Check' },
  'check-pequeno': { icon: Tick02Icon, label: 'Check pequeno' },
  'check-negrito': { icon: Tick02Icon, label: 'Check (traço grosso)', stroke: 2.6 },
  'check-circulo': { icon: CheckmarkCircle02Icon, label: 'Check em círculo' },
  pausar: { icon: PauseIcon, label: 'Pausar' },
  tocar: { icon: PlayIcon, label: 'Tocar' },
  som: { icon: VolumeHighIcon, label: 'Som ligado' },
  mudo: { icon: VolumeOffIcon, label: 'Mudo' },
  'tema-escuro': { icon: Moon02Icon, label: 'Tema escuro' },
  'tema-claro': { icon: Sun03Icon, label: 'Tema claro' },

  // compra e entrega
  sacola: { icon: ShoppingBag01Icon, label: 'Sacola do pedido' },
  'sacola-grande': { icon: ShoppingBag02Icon, label: 'Sacola (grande)' },
  caminhao: { icon: DeliveryTruck01Icon, label: 'Frete / entrega' },
  delivery: { icon: DeliveryTruck02Icon, label: 'Delivery' },
  loja: { icon: Store01Icon, label: 'Loja física' },
  recibo: { icon: ReceiptIcon, label: 'Recibo' },
  'nota-fiscal': { icon: Invoice01Icon, label: 'Nota fiscal' },
  presente: { icon: GiftIcon, label: 'Presente' },
  trocar: { icon: ArrowReloadHorizontalIcon, label: 'Trocar / renovar' },
  pote: { icon: Medicine01Icon, label: 'Pote do produto' },

  // a dor e o dia a dia
  prato: { icon: Dish01Icon, label: 'Prato' },
  'prato-talheres': { icon: Restaurant01Icon, label: 'Prato com talheres' },
  bala: { icon: CandyIcon, label: 'Bala' },
  'bala-riscada': { icon: CandyOffIcon, label: 'Bala riscada' },
  'biscoito-mordido': { icon: CookieIcon, label: 'Biscoito mordido' },
  'biscoito-grande': { icon: CookieIcon, label: 'Biscoito (grande)' },
  cupcake: { icon: Cupcake01Icon, label: 'Cupcake' },
  'tigela-quente': { icon: RiceBowl01Icon, label: 'Tigela quente' },
  lua: { icon: Moon02Icon, label: 'Lua' },
  'lua-grande': { icon: Moon02Icon, label: 'Lua (grande)' },
  calendario: { icon: Calendar03Icon, label: 'Calendário' },
  relogio: { icon: Clock01Icon, label: 'Relógio' },
  pulso: { icon: Activity03Icon, label: 'Pulso acelerado' },
  raio: { icon: FlashIcon, label: 'Raio' },
  'rosto-triste': { icon: Sad01Icon, label: 'Rosto triste' },
  'rosto-triste-grande': { icon: Sad01Icon, label: 'Rosto triste (ilustração)' },

  // ingredientes e ciência
  molecula: { icon: Atom01Icon, label: 'Molécula' },
  sementes: { icon: SproutIcon, label: 'Sementes' },
  'grao-cafe': { icon: CoffeeBeansIcon, label: 'Grão de café' },
  raiz: { icon: Leaf01Icon, label: 'Raiz / planta' },
  'sol-vitamina': { icon: Sun03Icon, label: 'Sol / vitamina D' },
  gota: { icon: DropletIcon, label: 'Gota' },
  'caneta-injecao': { icon: InjectionIcon, label: 'Injeção' },

  // confiança
  'escudo-alerta': { icon: Shield01Icon, label: 'Escudo com alerta' },
  'escudo-check': { icon: ShieldCheckIcon, label: 'Escudo com check' },
  cadeado: { icon: SquareLock01Icon, label: 'Cadeado' },
  'cadeado-24': { icon: SquareLock01Icon, label: 'Cadeado (24px)' },
  selo: { icon: CheckmarkBadge01Icon, label: 'Selo' },
  info: { icon: InformationCircleIcon, label: 'Informação' },
  ajuda: { icon: HelpCircleIcon, label: 'Ajuda / pergunta' },
  alerta: { icon: Alert02Icon, label: 'Alerta' },
  estrela: { icon: StarIcon, label: 'Estrela' },
  brilho: { icon: SparklesIcon, label: 'Brilho' },
  livro: { icon: Book02Icon, label: 'Livro' },
  'balao-conversa': { icon: Message01Icon, label: 'Balão de conversa' },
  'tendencia-alta': { icon: ChartUpIcon, label: 'Tendência de alta' },

  // redes
  whatsapp: { icon: WhatsappIcon, label: 'WhatsApp' },
  instagram: { icon: InstagramIcon, label: 'Instagram' },
  tiktok: { icon: TiktokIcon, label: 'TikTok' },
  facebook: { icon: Facebook01Icon, label: 'Facebook' },
  youtube: { icon: YoutubeIcon, label: 'YouTube' },
} satisfies Record<string, IconDef>

export type IconName = keyof typeof icons
