/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    ofertas: Oferta;
    'frete-gratis': FreteGrati;
    bonus: Bonus;
  };
  globalsSelect: {
    ofertas: OfertasSelect<false> | OfertasSelect<true>;
    'frete-gratis': FreteGratisSelect<false> | FreteGratisSelect<true>;
    bonus: BonusSelect<false> | BonusSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para quem usa leitor de tela.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome?: string | null;
  papel: 'rk' | 'cliente';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas".
 */
export interface Oferta {
  id: number;
  produto: {
    nome: string;
    capsulas?: string | null;
    diasPorPote?: number | null;
    foto?: (number | null) | Media;
  };
  pagamento?: {
    descontoPix?: number | null;
    parcelas?: number | null;
  };
  /**
   * Só para referência, ex.: Yampi, B4You, Shopify.
   */
  plataformaCheckout?: string | null;
  opcoes?:
    | {
        potes: number;
        preco: number;
        /**
         * Riscado ao lado do preço. Vazio esconde.
         */
        precoDe?: number | null;
        /**
         * Para onde o botão "Fazer pedido" leva com essa quantidade.
         */
        linkCheckout?: string | null;
        ativo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A barra no carrinho é só visual. O checkout precisa aplicar a mesma regra (subtotal a partir do valor mínimo = frete zero).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frete-gratis".
 */
export interface FreteGrati {
  id: number;
  /**
   * Desligado, some do carrinho e das ofertas.
   */
  ativo?: boolean | null;
  valorMinimo?: number | null;
  segmentos?: number | null;
  textoProgresso?: string | null;
  textoLiberado?: string | null;
  /**
   * {falta} vira o valor que falta.
   */
  subtextoProgresso?: string | null;
  subtextoLiberado?: string | null;
  comemorar?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus".
 */
export interface Bonus {
  id: number;
  /**
   * Desligado, a seção, os selos e os bônus do carrinho somem.
   */
  ativo?: boolean | null;
  subtitulo?: string | null;
  entrega?: string | null;
  itens?:
    | {
        titulo: string;
        descricao?: string | null;
        potesMinimos: number;
        valorDe?: number | null;
        icone?:
          | (
              | 'menu'
              | 'caminhao'
              | 'sacola'
              | 'fechar'
              | 'brilho'
              | 'chevron-cima'
              | 'seta-direita'
              | 'presente'
              | 'trocar'
              | 'ajuda'
              | 'prato'
              | 'bala'
              | 'biscoito-mordido'
              | 'lua'
              | 'calendario'
              | 'pulso'
              | 'x-pequeno'
              | 'rosto-triste-grande'
              | 'bala-riscada'
              | 'lua-grande'
              | 'tigela-quente'
              | 'raio'
              | 'rosto-triste'
              | 'x-circulo'
              | 'check-circulo'
              | 'mais'
              | 'molecula'
              | 'sementes'
              | 'grao-cafe'
              | 'raiz'
              | 'sol-vitamina'
              | 'chevron-esquerda'
              | 'chevron-direita'
              | 'gota'
              | 'relogio'
              | 'escudo-alerta'
              | 'selo'
              | 'info'
              | 'estrela'
              | 'check'
              | 'pote'
              | 'livro'
              | 'check-pequeno'
              | 'cadeado'
              | 'prato-talheres'
              | 'balao-conversa'
              | 'caneta-injecao'
              | 'delivery'
              | 'cupcake'
              | 'biscoito-grande'
              | 'sacola-grande'
              | 'loja'
              | 'recibo'
              | 'whatsapp'
              | 'tendencia-alta'
              | 'x-negrito'
              | 'check-negrito'
              | 'tema-escuro'
              | 'tema-claro'
              | 'pausar'
              | 'tocar'
              | 'som'
              | 'mudo'
              | 'mais-botao'
              | 'instagram'
              | 'tiktok'
              | 'facebook'
              | 'youtube'
              | 'escudo-check'
              | 'cadeado-24'
              | 'chevron-baixo'
              | 'nota-fiscal'
            )
          | null;
        /**
         * Usada no carrinho. Sem imagem, aparece um espaço reservado.
         */
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas_select".
 */
export interface OfertasSelect<T extends boolean = true> {
  produto?:
    | T
    | {
        nome?: T;
        capsulas?: T;
        diasPorPote?: T;
        foto?: T;
      };
  pagamento?:
    | T
    | {
        descontoPix?: T;
        parcelas?: T;
      };
  plataformaCheckout?: T;
  opcoes?:
    | T
    | {
        potes?: T;
        preco?: T;
        precoDe?: T;
        linkCheckout?: T;
        ativo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frete-gratis_select".
 */
export interface FreteGratisSelect<T extends boolean = true> {
  ativo?: T;
  valorMinimo?: T;
  segmentos?: T;
  textoProgresso?: T;
  textoLiberado?: T;
  subtextoProgresso?: T;
  subtextoLiberado?: T;
  comemorar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus_select".
 */
export interface BonusSelect<T extends boolean = true> {
  ativo?: T;
  subtitulo?: T;
  entrega?: T;
  itens?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        potesMinimos?: T;
        valorDe?: T;
        icone?: T;
        imagem?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}