/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    depoimentos: Depoimento;
    videos: Video;
    faq: Faq;
    ingredientes: Ingrediente;
    politicas: Politica;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    depoimentos: DepoimentosSelect<false> | DepoimentosSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    ingredientes: IngredientesSelect<false> | IngredientesSelect<true>;
    politicas: PoliticasSelect<false> | PoliticasSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    ofertas: Oferta;
    'frete-gratis': FreteGrati;
    bonus: Bonus;
    textos: Texto;
    'prova-social': ProvaSocial;
    contato: Contato;
    seo: Seo;
    cookies: Cooky;
  };
  globalsSelect: {
    ofertas: OfertasSelect<false> | OfertasSelect<true>;
    'frete-gratis': FreteGratisSelect<false> | FreteGratisSelect<true>;
    bonus: BonusSelect<false> | BonusSelect<true>;
    textos: TextosSelect<false> | TextosSelect<true>;
    'prova-social': ProvaSocialSelect<false> | ProvaSocialSelect<true>;
    contato: ContatoSelect<false> | ContatoSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    cookies: CookiesSelect<false> | CookiesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  _order?: string | null;
  titulo: string;
  /**
   * Opcional. Com print, ele substitui as mensagens abaixo. Cubra o telefone.
   */
  print?: (number | null) | Media;
  mensagens?:
    | {
        texto: string;
        hora?: string | null;
        lado?: ('cliente' | 'loja') | null;
        id?: string | null;
      }[]
    | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreva a imagem para quem usa leitor de tela.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  _order?: string | null;
  tema: string;
  nome: string;
  legenda?: string | null;
  video?: (number | null) | Media;
  /**
   * Opcional. Imagem antes do vídeo carregar.
   */
  capa?: (number | null) | Media;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  pergunta: string;
  resposta: string;
  aberta?: boolean | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredientes".
 */
export interface Ingrediente {
  id: number;
  _order?: string | null;
  nome: string;
  beneficio: string;
  dosagem?: string | null;
  foto?: (number | null) | Media;
  icone?:
    | (
        | 'menu'
        | 'caminhao'
        | 'sacola'
        | 'fechar'
        | 'brilho'
        | 'chevron-cima'
        | 'seta-direita'
        | 'presente'
        | 'trocar'
        | 'ajuda'
        | 'prato'
        | 'bala'
        | 'biscoito-mordido'
        | 'lua'
        | 'calendario'
        | 'pulso'
        | 'x-pequeno'
        | 'rosto-triste-grande'
        | 'bala-riscada'
        | 'lua-grande'
        | 'tigela-quente'
        | 'raio'
        | 'rosto-triste'
        | 'x-circulo'
        | 'check-circulo'
        | 'mais'
        | 'molecula'
        | 'sementes'
        | 'grao-cafe'
        | 'raiz'
        | 'sol-vitamina'
        | 'chevron-esquerda'
        | 'chevron-direita'
        | 'gota'
        | 'relogio'
        | 'escudo-alerta'
        | 'selo'
        | 'info'
        | 'estrela'
        | 'check'
        | 'pote'
        | 'livro'
        | 'check-pequeno'
        | 'cadeado'
        | 'prato-talheres'
        | 'balao-conversa'
        | 'caneta-injecao'
        | 'delivery'
        | 'cupcake'
        | 'biscoito-grande'
        | 'sacola-grande'
        | 'loja'
        | 'recibo'
        | 'whatsapp'
        | 'tendencia-alta'
        | 'x-negrito'
        | 'check-negrito'
        | 'tema-escuro'
        | 'tema-claro'
        | 'pausar'
        | 'tocar'
        | 'som'
        | 'mudo'
        | 'mais-botao'
        | 'instagram'
        | 'tiktok'
        | 'facebook'
        | 'youtube'
        | 'escudo-check'
        | 'cadeado-24'
        | 'chevron-baixo'
        | 'nota-fiscal'
      )
    | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicas".
 */
export interface Politica {
  id: number;
  _order?: string | null;
  titulo: string;
  /**
   * Parte final da URL, ex.: politica-de-privacidade
   */
  slug: string;
  atualizado?: string | null;
  intro?: string | null;
  conteudo: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome?: string | null;
  papel: 'rk' | 'cliente';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'depoimentos';
        value: number | Depoimento;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'ingredientes';
        value: number | Ingrediente;
      } | null)
    | ({
        relationTo: 'politicas';
        value: number | Politica;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos_select".
 */
export interface DepoimentosSelect<T extends boolean = true> {
  _order?: T;
  titulo?: T;
  print?: T;
  mensagens?:
    | T
    | {
        texto?: T;
        hora?: T;
        lado?: T;
        id?: T;
      };
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  _order?: T;
  tema?: T;
  nome?: T;
  legenda?: T;
  video?: T;
  capa?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  _order?: T;
  pergunta?: T;
  resposta?: T;
  aberta?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredientes_select".
 */
export interface IngredientesSelect<T extends boolean = true> {
  _order?: T;
  nome?: T;
  beneficio?: T;
  dosagem?: T;
  foto?: T;
  icone?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "politicas_select".
 */
export interface PoliticasSelect<T extends boolean = true> {
  _order?: T;
  titulo?: T;
  slug?: T;
  atualizado?: T;
  intro?: T;
  conteudo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  papel?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas".
 */
export interface Oferta {
  id: number;
  produto: {
    nome: string;
    capsulas?: string | null;
    diasPorPote?: number | null;
    foto?: (number | null) | Media;
  };
  pagamento?: {
    descontoPix?: number | null;
    parcelas?: number | null;
  };
  /**
   * Só para referência, ex.: Yampi, B4You, Shopify.
   */
  plataformaCheckout?: string | null;
  opcoes?:
    | {
        potes: number;
        preco: number;
        /**
         * Riscado ao lado do preço. Vazio esconde.
         */
        precoDe?: number | null;
        /**
         * Para onde o botão "Fazer pedido" leva com essa quantidade.
         */
        linkCheckout?: string | null;
        ativo?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A barra no carrinho é só visual. O checkout precisa aplicar a mesma regra (subtotal a partir do valor mínimo = frete zero).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frete-gratis".
 */
export interface FreteGrati {
  id: number;
  /**
   * Desligado, some do carrinho e das ofertas.
   */
  ativo?: boolean | null;
  valorMinimo?: number | null;
  segmentos?: number | null;
  textoProgresso?: string | null;
  textoLiberado?: string | null;
  /**
   * {falta} vira o valor que falta.
   */
  subtextoProgresso?: string | null;
  subtextoLiberado?: string | null;
  comemorar?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus".
 */
export interface Bonus {
  id: number;
  /**
   * Desligado, a seção, os selos e os bônus do carrinho somem.
   */
  ativo?: boolean | null;
  subtitulo?: string | null;
  entrega?: string | null;
  itens?:
    | {
        titulo: string;
        descricao?: string | null;
        potesMinimos: number;
        valorDe?: number | null;
        icone?:
          | (
              | 'menu'
              | 'caminhao'
              | 'sacola'
              | 'fechar'
              | 'brilho'
              | 'chevron-cima'
              | 'seta-direita'
              | 'presente'
              | 'trocar'
              | 'ajuda'
              | 'prato'
              | 'bala'
              | 'biscoito-mordido'
              | 'lua'
              | 'calendario'
              | 'pulso'
              | 'x-pequeno'
              | 'rosto-triste-grande'
              | 'bala-riscada'
              | 'lua-grande'
              | 'tigela-quente'
              | 'raio'
              | 'rosto-triste'
              | 'x-circulo'
              | 'check-circulo'
              | 'mais'
              | 'molecula'
              | 'sementes'
              | 'grao-cafe'
              | 'raiz'
              | 'sol-vitamina'
              | 'chevron-esquerda'
              | 'chevron-direita'
              | 'gota'
              | 'relogio'
              | 'escudo-alerta'
              | 'selo'
              | 'info'
              | 'estrela'
              | 'check'
              | 'pote'
              | 'livro'
              | 'check-pequeno'
              | 'cadeado'
              | 'prato-talheres'
              | 'balao-conversa'
              | 'caneta-injecao'
              | 'delivery'
              | 'cupcake'
              | 'biscoito-grande'
              | 'sacola-grande'
              | 'loja'
              | 'recibo'
              | 'whatsapp'
              | 'tendencia-alta'
              | 'x-negrito'
              | 'check-negrito'
              | 'tema-escuro'
              | 'tema-claro'
              | 'pausar'
              | 'tocar'
              | 'som'
              | 'mudo'
              | 'mais-botao'
              | 'instagram'
              | 'tiktok'
              | 'facebook'
              | 'youtube'
              | 'escudo-check'
              | 'cadeado-24'
              | 'chevron-baixo'
              | 'nota-fiscal'
            )
          | null;
        /**
         * Usada no carrinho. Sem imagem, aparece um espaço reservado.
         */
        imagem?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos".
 */
export interface Texto {
  id: number;
  hero: {
    etiqueta?: string | null;
    titulo: string;
    tituloLeve?: string | null;
    /**
     * Use **texto** para negrito.
     */
    subtitulo?: string | null;
    /**
     * Use **texto** para negrito.
     */
    condicao?: string | null;
    foto?: (number | null) | Media;
    /**
     * O menu que abre no ícone ☰ do topo. Links são âncoras de seção, como #oferta.
     */
    menu?: {
      destaque?: {
        texto?: string | null;
        link?: string | null;
        icone?:
          | (
              | 'menu'
              | 'caminhao'
              | 'sacola'
              | 'fechar'
              | 'brilho'
              | 'chevron-cima'
              | 'seta-direita'
              | 'presente'
              | 'trocar'
              | 'ajuda'
              | 'prato'
              | 'bala'
              | 'biscoito-mordido'
              | 'lua'
              | 'calendario'
              | 'pulso'
              | 'x-pequeno'
              | 'rosto-triste-grande'
              | 'bala-riscada'
              | 'lua-grande'
              | 'tigela-quente'
              | 'raio'
              | 'rosto-triste'
              | 'x-circulo'
              | 'check-circulo'
              | 'mais'
              | 'molecula'
              | 'sementes'
              | 'grao-cafe'
              | 'raiz'
              | 'sol-vitamina'
              | 'chevron-esquerda'
              | 'chevron-direita'
              | 'gota'
              | 'relogio'
              | 'escudo-alerta'
              | 'selo'
              | 'info'
              | 'estrela'
              | 'check'
              | 'pote'
              | 'livro'
              | 'check-pequeno'
              | 'cadeado'
              | 'prato-talheres'
              | 'balao-conversa'
              | 'caneta-injecao'
              | 'delivery'
              | 'cupcake'
              | 'biscoito-grande'
              | 'sacola-grande'
              | 'loja'
              | 'recibo'
              | 'whatsapp'
              | 'tendencia-alta'
              | 'x-negrito'
              | 'check-negrito'
              | 'tema-escuro'
              | 'tema-claro'
              | 'pausar'
              | 'tocar'
              | 'som'
              | 'mudo'
              | 'mais-botao'
              | 'instagram'
              | 'tiktok'
              | 'facebook'
              | 'youtube'
              | 'escudo-check'
              | 'cadeado-24'
              | 'chevron-baixo'
              | 'nota-fiscal'
            )
          | null;
      };
      conheca?: {
        titulo?: string | null;
        icone?:
          | (
              | 'menu'
              | 'caminhao'
              | 'sacola'
              | 'fechar'
              | 'brilho'
              | 'chevron-cima'
              | 'seta-direita'
              | 'presente'
              | 'trocar'
              | 'ajuda'
              | 'prato'
              | 'bala'
              | 'biscoito-mordido'
              | 'lua'
              | 'calendario'
              | 'pulso'
              | 'x-pequeno'
              | 'rosto-triste-grande'
              | 'bala-riscada'
              | 'lua-grande'
              | 'tigela-quente'
              | 'raio'
              | 'rosto-triste'
              | 'x-circulo'
              | 'check-circulo'
              | 'mais'
              | 'molecula'
              | 'sementes'
              | 'grao-cafe'
              | 'raiz'
              | 'sol-vitamina'
              | 'chevron-esquerda'
              | 'chevron-direita'
              | 'gota'
              | 'relogio'
              | 'escudo-alerta'
              | 'selo'
              | 'info'
              | 'estrela'
              | 'check'
              | 'pote'
              | 'livro'
              | 'check-pequeno'
              | 'cadeado'
              | 'prato-talheres'
              | 'balao-conversa'
              | 'caneta-injecao'
              | 'delivery'
              | 'cupcake'
              | 'biscoito-grande'
              | 'sacola-grande'
              | 'loja'
              | 'recibo'
              | 'whatsapp'
              | 'tendencia-alta'
              | 'x-negrito'
              | 'check-negrito'
              | 'tema-escuro'
              | 'tema-claro'
              | 'pausar'
              | 'tocar'
              | 'som'
              | 'mudo'
              | 'mais-botao'
              | 'instagram'
              | 'tiktok'
              | 'facebook'
              | 'youtube'
              | 'escudo-check'
              | 'cadeado-24'
              | 'chevron-baixo'
              | 'nota-fiscal'
            )
          | null;
        cards?:
          | {
              linha1?: string | null;
              linha2?: string | null;
              link?: string | null;
              /**
               * Sem foto, aparece o espaço reservado.
               */
              foto?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
      };
      /**
       * O item com link #bonus some quando os bônus estão desligados.
       */
      itens?:
        | {
            texto: string;
            link: string;
            icone?:
              | (
                  | 'menu'
                  | 'caminhao'
                  | 'sacola'
                  | 'fechar'
                  | 'brilho'
                  | 'chevron-cima'
                  | 'seta-direita'
                  | 'presente'
                  | 'trocar'
                  | 'ajuda'
                  | 'prato'
                  | 'bala'
                  | 'biscoito-mordido'
                  | 'lua'
                  | 'calendario'
                  | 'pulso'
                  | 'x-pequeno'
                  | 'rosto-triste-grande'
                  | 'bala-riscada'
                  | 'lua-grande'
                  | 'tigela-quente'
                  | 'raio'
                  | 'rosto-triste'
                  | 'x-circulo'
                  | 'check-circulo'
                  | 'mais'
                  | 'molecula'
                  | 'sementes'
                  | 'grao-cafe'
                  | 'raiz'
                  | 'sol-vitamina'
                  | 'chevron-esquerda'
                  | 'chevron-direita'
                  | 'gota'
                  | 'relogio'
                  | 'escudo-alerta'
                  | 'selo'
                  | 'info'
                  | 'estrela'
                  | 'check'
                  | 'pote'
                  | 'livro'
                  | 'check-pequeno'
                  | 'cadeado'
                  | 'prato-talheres'
                  | 'balao-conversa'
                  | 'caneta-injecao'
                  | 'delivery'
                  | 'cupcake'
                  | 'biscoito-grande'
                  | 'sacola-grande'
                  | 'loja'
                  | 'recibo'
                  | 'whatsapp'
                  | 'tendencia-alta'
                  | 'x-negrito'
                  | 'check-negrito'
                  | 'tema-escuro'
                  | 'tema-claro'
                  | 'pausar'
                  | 'tocar'
                  | 'som'
                  | 'mudo'
                  | 'mais-botao'
                  | 'instagram'
                  | 'tiktok'
                  | 'facebook'
                  | 'youtube'
                  | 'escudo-check'
                  | 'cadeado-24'
                  | 'chevron-baixo'
                  | 'nota-fiscal'
                )
              | null;
            id?: string | null;
          }[]
        | null;
      rodape?: string | null;
    };
  };
  dor?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    chamada?: string | null;
    dia?:
      | {
          titulo: string;
          texto: string;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Sem foto, aparece o espaço reservado.
     */
    foto?: (number | null) | Media;
    /**
     * Até 4. Cada posição tem seu lugar fixo em volta da foto.
     */
    baloes?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    fecho1?: string | null;
    fecho2?: string | null;
    fecho3?: string | null;
  };
  naoCulpa?: {
    /**
     * Sem foto, aparece o espaço reservado.
     */
    foto?: (number | null) | Media;
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    tentativas?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    cards?:
      | {
          titulo: string;
          texto?: string | null;
          id?: string | null;
        }[]
      | null;
    destaque?: string | null;
    destaqueTag?: string | null;
    destaqueTexto?: string | null;
    fecho1?: string | null;
    fecho2?: string | null;
    fecho3?: string | null;
    /**
     * Vazio usa a linha 3.
     */
    fecho3Celular?: string | null;
    /**
     * Repete em loop na faixa preta.
     */
    faixa?: string | null;
  };
  destaque?: {
    linha1?: string | null;
    linha2?: string | null;
    linha2b?: string | null;
    linha3?: string | null;
    subtitulo?: string | null;
    /**
     * As fotos passam em loop. As alturas variam sozinhas.
     */
    fotos?:
      | {
          /**
           * Sem foto, aparece o espaço reservado.
           */
          foto?: (number | null) | Media;
          titulo?: string | null;
          /**
           * Aparece no espaço enquanto não há foto.
           */
          texto?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  produto?: {
    /**
     * Use **texto** para negrito.
     */
    paragrafo1?: string | null;
    /**
     * Use **texto** para negrito.
     */
    paragrafo2?: string | null;
    sentirTitulo?: string | null;
    sentirTexto?: string | null;
    sentir?:
      | {
          /**
           * Aperte Enter onde a linha deve quebrar.
           */
          texto: string;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    tabelaTitulo?: string | null;
    tabelaSem?: string | null;
    tabelaCom?: string | null;
    tabela?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    fecho?: string | null;
    fechoLeve?: string | null;
  };
  depoimentos?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    subtitulo?: string | null;
    /**
     * Sem foto, aparece o espaço reservado.
     */
    foto?: (number | null) | Media;
    painelTitulo?: string | null;
    painelSubtitulo?: string | null;
  };
  videos?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    subtitulo?: string | null;
  };
  ingredientes?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    porcao?: string | null;
    /**
     * Use **texto** para negrito.
     */
    comoUsar?: string | null;
  };
  jaUsa?: {
    etiqueta?: string | null;
    titulo1?: string | null;
    titulo2?: string | null;
    titulo3?: string | null;
    subtitulo?: string | null;
    vantagens?:
      | {
          texto: string;
          id?: string | null;
        }[]
      | null;
    forte?: string | null;
    tickerRotulo?: string | null;
    /**
     * Texto e foto trocam juntos a cada 2,6 s.
     */
    ticker?:
      | {
          texto: string;
          /**
           * Sem foto, aparece o espaço reservado.
           */
          foto?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  bonus?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
  };
  oferta?: {
    /**
     * Texto curto: fica sempre em uma linha.
     */
    etiqueta?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    gastos?:
      | {
          texto: string;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * {produto} vira o nome do produto e {valor} o preço por dia.
     */
    fraseGastos?: string | null;
    cardEtiqueta?: string | null;
    escolha?: string | null;
    /**
     * Use **texto** para negrito.
     */
    garantia?: string | null;
    /**
     * {valor} vira o preço por dia do pote avulso.
     */
    precoPorDia?: string | null;
    confianca?:
      | {
          titulo: string;
          texto?: string | null;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  duvidas?: {
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    /**
     * Sem imagem, aparece o espaço reservado.
     */
    ilustracao?: (number | null) | Media;
    avisosTitulo?: string | null;
    avisosTexto?: string | null;
    /**
     * Trocam sozinhos a cada 5 s.
     */
    avisos?:
      | {
          rotulo?: string | null;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          titulo: string;
          texto?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  final?: {
    /**
     * Sem foto, aparece o espaço reservado.
     */
    foto?: (number | null) | Media;
    chamada?: string | null;
    titulo?: string | null;
    /**
     * Continua o título com letra fina.
     */
    tituloLeve?: string | null;
    /**
     * Use **texto** para negrito.
     */
    opcaoNao?: string | null;
    /**
     * Use **texto** para negrito.
     */
    opcaoSim?: string | null;
    frase?: string | null;
  };
  rodape?: {
    /**
     * Aperte Enter onde a linha deve quebrar.
     */
    faixa?: string | null;
    tituloAtendimento?: string | null;
    tituloPagamento?: string | null;
    selos?:
      | {
          titulo: string;
          texto?: string | null;
          icone?:
            | (
                | 'menu'
                | 'caminhao'
                | 'sacola'
                | 'fechar'
                | 'brilho'
                | 'chevron-cima'
                | 'seta-direita'
                | 'presente'
                | 'trocar'
                | 'ajuda'
                | 'prato'
                | 'bala'
                | 'biscoito-mordido'
                | 'lua'
                | 'calendario'
                | 'pulso'
                | 'x-pequeno'
                | 'rosto-triste-grande'
                | 'bala-riscada'
                | 'lua-grande'
                | 'tigela-quente'
                | 'raio'
                | 'rosto-triste'
                | 'x-circulo'
                | 'check-circulo'
                | 'mais'
                | 'molecula'
                | 'sementes'
                | 'grao-cafe'
                | 'raiz'
                | 'sol-vitamina'
                | 'chevron-esquerda'
                | 'chevron-direita'
                | 'gota'
                | 'relogio'
                | 'escudo-alerta'
                | 'selo'
                | 'info'
                | 'estrela'
                | 'check'
                | 'pote'
                | 'livro'
                | 'check-pequeno'
                | 'cadeado'
                | 'prato-talheres'
                | 'balao-conversa'
                | 'caneta-injecao'
                | 'delivery'
                | 'cupcake'
                | 'biscoito-grande'
                | 'sacola-grande'
                | 'loja'
                | 'recibo'
                | 'whatsapp'
                | 'tendencia-alta'
                | 'x-negrito'
                | 'check-negrito'
                | 'tema-escuro'
                | 'tema-claro'
                | 'pausar'
                | 'tocar'
                | 'som'
                | 'mudo'
                | 'mais-botao'
                | 'instagram'
                | 'tiktok'
                | 'facebook'
                | 'youtube'
                | 'escudo-check'
                | 'cadeado-24'
                | 'chevron-baixo'
                | 'nota-fiscal'
              )
            | null;
          id?: string | null;
        }[]
      | null;
  };
  botoes?: {
    principal?: string | null;
    produto?: string | null;
    bonus?: string | null;
    pedido?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prova-social".
 */
export interface ProvaSocial {
  id: number;
  anuncios?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  selo?: {
    numero?: string | null;
    texto?: string | null;
  };
  /**
   * Use **texto** para negrito.
   */
  provaHero?: string | null;
  numeros?:
    | {
        valor: number;
        sufixo?: string | null;
        legenda: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contato".
 */
export interface Contato {
  id: number;
  whatsapp?: string | null;
  whatsappExibicao?: string | null;
  whatsappMensagem?: string | null;
  lojaTexto?: string | null;
  lojaMaps?: string | null;
  redes?: {
    /**
     * Vazio esconde o ícone.
     */
    instagram?: string | null;
    /**
     * Vazio esconde o ícone.
     */
    tiktok?: string | null;
    /**
     * Vazio esconde o ícone.
     */
    facebook?: string | null;
    /**
     * Vazio esconde o ícone.
     */
    youtube?: string | null;
  };
  /**
   * O grupo Atendimento (WhatsApp, loja e políticas) é montado sozinho com os dados acima.
   */
  grupos?:
    | {
        titulo: string;
        links?:
          | {
              rotulo: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  formasPagamento?: ('Visa' | 'Mastercard' | 'Amex' | 'Elo' | 'Hipercard' | 'Diners' | 'Pix')[] | null;
  avisoLegal?: string | null;
  /**
   * Razão social, CNPJ, endereço e SAC.
   */
  empresa?: string | null;
  copyright?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  titulo?: string | null;
  descricao?: string | null;
  /**
   * 1200 × 630 px.
   */
  imagem?: (number | null) | Media;
  /**
   * Imagem quadrada, PNG ou SVG. Vazio usa o "A" da ALPHA.
   */
  favicon?: (number | null) | Media;
  indexar?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies".
 */
export interface Cooky {
  id: number;
  ativo?: boolean | null;
  /**
   * O link para a Política de privacidade entra no final, automaticamente.
   */
  texto?: string | null;
  botao?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ofertas_select".
 */
export interface OfertasSelect<T extends boolean = true> {
  produto?:
    | T
    | {
        nome?: T;
        capsulas?: T;
        diasPorPote?: T;
        foto?: T;
      };
  pagamento?:
    | T
    | {
        descontoPix?: T;
        parcelas?: T;
      };
  plataformaCheckout?: T;
  opcoes?:
    | T
    | {
        potes?: T;
        preco?: T;
        precoDe?: T;
        linkCheckout?: T;
        ativo?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frete-gratis_select".
 */
export interface FreteGratisSelect<T extends boolean = true> {
  ativo?: T;
  valorMinimo?: T;
  segmentos?: T;
  textoProgresso?: T;
  textoLiberado?: T;
  subtextoProgresso?: T;
  subtextoLiberado?: T;
  comemorar?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bonus_select".
 */
export interface BonusSelect<T extends boolean = true> {
  ativo?: T;
  subtitulo?: T;
  entrega?: T;
  itens?:
    | T
    | {
        titulo?: T;
        descricao?: T;
        potesMinimos?: T;
        valorDe?: T;
        icone?: T;
        imagem?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos_select".
 */
export interface TextosSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        subtitulo?: T;
        condicao?: T;
        foto?: T;
        menu?:
          | T
          | {
              destaque?:
                | T
                | {
                    texto?: T;
                    link?: T;
                    icone?: T;
                  };
              conheca?:
                | T
                | {
                    titulo?: T;
                    icone?: T;
                    cards?:
                      | T
                      | {
                          linha1?: T;
                          linha2?: T;
                          link?: T;
                          foto?: T;
                          id?: T;
                        };
                  };
              itens?:
                | T
                | {
                    texto?: T;
                    link?: T;
                    icone?: T;
                    id?: T;
                  };
              rodape?: T;
            };
      };
  dor?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        chamada?: T;
        dia?:
          | T
          | {
              titulo?: T;
              texto?: T;
              icone?: T;
              id?: T;
            };
        foto?: T;
        baloes?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        fecho1?: T;
        fecho2?: T;
        fecho3?: T;
      };
  naoCulpa?:
    | T
    | {
        foto?: T;
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        tentativas?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        cards?:
          | T
          | {
              titulo?: T;
              texto?: T;
              id?: T;
            };
        destaque?: T;
        destaqueTag?: T;
        destaqueTexto?: T;
        fecho1?: T;
        fecho2?: T;
        fecho3?: T;
        fecho3Celular?: T;
        faixa?: T;
      };
  destaque?:
    | T
    | {
        linha1?: T;
        linha2?: T;
        linha2b?: T;
        linha3?: T;
        subtitulo?: T;
        fotos?:
          | T
          | {
              foto?: T;
              titulo?: T;
              texto?: T;
              id?: T;
            };
      };
  produto?:
    | T
    | {
        paragrafo1?: T;
        paragrafo2?: T;
        sentirTitulo?: T;
        sentirTexto?: T;
        sentir?:
          | T
          | {
              texto?: T;
              icone?: T;
              id?: T;
            };
        tabelaTitulo?: T;
        tabelaSem?: T;
        tabelaCom?: T;
        tabela?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        fecho?: T;
        fechoLeve?: T;
      };
  depoimentos?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        subtitulo?: T;
        foto?: T;
        painelTitulo?: T;
        painelSubtitulo?: T;
      };
  videos?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        subtitulo?: T;
      };
  ingredientes?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        porcao?: T;
        comoUsar?: T;
      };
  jaUsa?:
    | T
    | {
        etiqueta?: T;
        titulo1?: T;
        titulo2?: T;
        titulo3?: T;
        subtitulo?: T;
        vantagens?:
          | T
          | {
              texto?: T;
              id?: T;
            };
        forte?: T;
        tickerRotulo?: T;
        ticker?:
          | T
          | {
              texto?: T;
              foto?: T;
              id?: T;
            };
      };
  bonus?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
      };
  oferta?:
    | T
    | {
        etiqueta?: T;
        titulo?: T;
        tituloLeve?: T;
        gastos?:
          | T
          | {
              texto?: T;
              icone?: T;
              id?: T;
            };
        fraseGastos?: T;
        cardEtiqueta?: T;
        escolha?: T;
        garantia?: T;
        precoPorDia?: T;
        confianca?:
          | T
          | {
              titulo?: T;
              texto?: T;
              icone?: T;
              id?: T;
            };
      };
  duvidas?:
    | T
    | {
        titulo?: T;
        tituloLeve?: T;
        ilustracao?: T;
        avisosTitulo?: T;
        avisosTexto?: T;
        avisos?:
          | T
          | {
              rotulo?: T;
              icone?: T;
              titulo?: T;
              texto?: T;
              id?: T;
            };
      };
  final?:
    | T
    | {
        foto?: T;
        chamada?: T;
        titulo?: T;
        tituloLeve?: T;
        opcaoNao?: T;
        opcaoSim?: T;
        frase?: T;
      };
  rodape?:
    | T
    | {
        faixa?: T;
        tituloAtendimento?: T;
        tituloPagamento?: T;
        selos?:
          | T
          | {
              titulo?: T;
              texto?: T;
              icone?: T;
              id?: T;
            };
      };
  botoes?:
    | T
    | {
        principal?: T;
        produto?: T;
        bonus?: T;
        pedido?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prova-social_select".
 */
export interface ProvaSocialSelect<T extends boolean = true> {
  anuncios?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  selo?:
    | T
    | {
        numero?: T;
        texto?: T;
      };
  provaHero?: T;
  numeros?:
    | T
    | {
        valor?: T;
        sufixo?: T;
        legenda?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contato_select".
 */
export interface ContatoSelect<T extends boolean = true> {
  whatsapp?: T;
  whatsappExibicao?: T;
  whatsappMensagem?: T;
  lojaTexto?: T;
  lojaMaps?: T;
  redes?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        facebook?: T;
        youtube?: T;
      };
  grupos?:
    | T
    | {
        titulo?: T;
        links?:
          | T
          | {
              rotulo?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  formasPagamento?: T;
  avisoLegal?: T;
  empresa?: T;
  copyright?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  titulo?: T;
  descricao?: T;
  imagem?: T;
  favicon?: T;
  indexar?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies_select".
 */
export interface CookiesSelect<T extends boolean = true> {
  ativo?: T;
  texto?: T;
  botao?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}